Autotest Implementation | Automate test cases from the 'Home Page' suite
vitali-akulau/Cypress pull request #2
Opened 2020-11-16 17:53 UTC by vitali-akulau

1. Implement autotests for the 'Home Page' suite
   - '**Verify ONE** section of the navigation menu' test case
   - '**MAIN MENU** verification' test case
   - '**QUICK SEARCH** verification' test case
   - '**ADVANCED SEARCH** verification' test case
2. Delete 'cypress' code examples from the framework

2020-11-17 08:57 UTC, KirylParkhomenka requested changes
@vitali-akulau Please update current PR due to my comments.
Overall tests look good. Great job!

After you will make updates - next task will be to implement in the current test:
- PO pattern
- Move test data to a separate files.

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/integration/examples/home_page.spec.js
> +    cy.get('#closeNotification', { timeout:10000 }).should('be.visible').click()
If chained commands have more than 2 commands, it will be more readable to write such command in the next way:
```
cy.get('#closeNotification', { timeout:10000 })
   .should('be.visible')
   .click()
```
Please update all places with such cases.

Note:
No need to update e.g.:
`cy.get('#closeNotification', { timeout:10000 }).should('be.visible')`

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/integration/examples/home_page.spec.js
> +  it('Verify one section of the navigation menu', () => {
I suppose that you are checking a particular section each time. So please specify the title of section instead of 'one section'.

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/integration/examples/home_page.spec.js
> +  it('Main menu verification', () => {
It's a good practice to use logging during tests. It will help customers to understand what is happening during the test execution, when they will read the report.
You can briefly describe what you are doing in:
 `cy.log('Each menu item has appropriate subtitles')`

Please note, that it's **not** a **necessary** point to do.
So please don't use it anywhere - only in some complicated code places, like these.

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/integration/examples/home_page.spec.js
> +    cy.get('div#advsearch_search_button').click()
As for me I will paste an empty line after #42 - will be more beautiful.

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/test_data/main_menu.js
> +    'HIP',
If you use 2 space symbols in tests - please use them everywhere instead of Tab.

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/test_data/search.js
> +export const ADVANCED_SEARCH_FULL_TEXT_FIELD = 'The apparently physiological kinematics of the bicruciate-stabilized \
You can use `\n` to create a transfer to a new string

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/test_data/main_menu.js
> +];
Either you use `;` everywhere - or no. Please decide 😸

2020-11-17 08:57 UTC, KirylParkhomenka commented on cypress/test_data/search.js
> +
If you decide to separate constants by different logic blocks - it will be useful to use comments - to describe block title, instead of pasting empty line. E.g.:
Either
```
export const TITLE_1 = '';
export const TITLE_2 = '';
```
OR
```
// Block 1
export const TITLE_1 = '';

// Block 2
export const TITLE_2 = '';
```

2020-11-17 08:57 UTC, KirylParkhomenka commented on jsconfig.json
> +{
Tabs or spaces 🥺

2020-11-17 19:37 UTC, vitali-akulau commented on cypress/test_data/search.js
> +export const ADVANCED_SEARCH_FULL_TEXT_FIELD = 'The apparently physiological kinematics of the bicruciate-stabilized \
I suggest changing this by using backquotes ``. It will be not necessary to use operators like '\' or '\n'.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/19670029/99438799-5ca86280-2925-11eb-8b8e-844543bc5569.png">

2020-11-19 07:31 UTC, KirylParkhomenka approved these changes

2020-11-19 07:31 UTC, KirylParkhomenka commented on cypress/integration/examples/home_page.spec.js
> +        .should('be.visible')
`should` must be under `get`. The same for `click`

2020-11-19 07:31 UTC, KirylParkhomenka commented on cypress/integration/examples/home_page.spec.js
> +        .should('be.visible')
But for now, let's leave as it is - anyway you will remove it to a separate PO file.

2020-11-19 08:26 UTC, merged