Enhancement | Apply 'Page Object' approach for Home Page tests suite
vitali-akulau/Cypress pull request #3
Opened 2020-11-20 22:39 UTC by vitali-akulau

1. Apply 'Page Object' approach for Home Page tests suite
   - Move all actions on pages to separate files
2. Add logging for the actions in the web pages

---

**Note**: [Video record](https://dashboard.cypress.io/projects/qejcs7/runs/6/specs/fcb290bc-33b0-47e5-b1bb-2feda571e2b2/video?utm_source=Dashboard&utm_medium=Share+URL&utm_campaign=Video)

2020-11-21 03:58 UTC, KirylParkhomenka requested changes
Summary:
1. Remember about code reusability.
2. Use parameters in methods.
3. Store all text in variables in a separate files.
4. Don't create a separate method for a single action.
5. Use hardcoded loggers only, if a method will be used for a single set of actions. In other way - use loggers directly in the test file.
6. Never use assertion outside the test file.

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/AdvancedSearchPage.js
> +import { SearchResultPage } from './SearchResultPage';
Is there any difference between import with and without figure brackets?
If no - please use the same import style everywhere.

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/AdvancedSearchPage.js
> +  allFieldsField = 'input[placeholder="knee"]';
Will be better to name it `allFieldsInput`

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/AdvancedSearchPage.js
> +  titleField = '#advsearch_title_box div:nth-child(2) input';
The same. Please try to name fields in order with their roles in the app. If it is an input - name it using `input` word. If it is a dropdown - using `dropdown`, etc.

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/AdvancedSearchPage.js
> +      .type('Knee Joint{esc}');
Please implement additional level of abstraction - move text into variables and store them in a separate file.

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/AdvancedSearchPage.js
> +  executeAdvancedSearch(){
You should create reusable methods.
Add parameters to your methods instead of hardcoded text.

E.g.
```
methodName(var1, var2) {
  cy.get(el).clear().type(var1 + '{esc}');
  cy.get(el).clear().type(var2 + '{esc}');
}
```
After it you will be able to pass any text to your methods in test file.

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/HomePage.js
> +  clinicalSummariesSectionItems = '#d_base_menu_block_0 ul li:nth-child(11) li';
Just a recommendation:
If you have locators with duplicated css parts, you can use next approach. It will help you to avoid updating **each** similar locator, after markup in the app will be changed.

```
clinicalSummariesSection = '#d_base_menu_block_0 ul li:nth-child(11)';
clinicalSummariesSectionItems = this.clinicalSummariesSection + ' li';
```

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/HomePage.js
> +    cy.log('Go to the \'JB&JS\' homepage');
I'm not agree with using hardcoded log message here.
You should always think about reusability of your code.

Current method can be used in next tests to open the page, different from Home page.
So you should:
1. Add logger directly in test file.
2. Move url to a parameter:
```
openPage(url){
  cy.visit(url);
  cy.get(this.acceptCookiesNotification, { timeout:10000 })
    .should('be.visible')
    .click();
  };

```

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/HomePage.js
> +  expandClinicalSummariesSection(){
No need to create a separate method for a single action.
Here you created 5 lines of code, but in the test you can use only 2 of them:
```
cy.log('Click on the \'CLINICAL SUMMARIES\' section in navigation menu');
    cy.get(this.clinicalSummariesSection).click();
```

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/HomePage.js
> +  openAdvancedSearchPage(){
The same as comment for line 44

2020-11-21 03:58 UTC, KirylParkhomenka commented on cypress/page_object/SearchResultPage.js
> +  validateQuickSearchResult(){
**Never use assertions in PO!!!**
PO - class which contains locators and methods to work with them.

2020-11-21 21:13 UTC, vitali-akulau commented on cypress/page_object/AdvancedSearchPage.js
> +import { SearchResultPage } from './SearchResultPage';
I use { SearchResultPage } for situation when I have to return type SearchResultPage from function

2020-11-23 16:21 UTC, KirylParkhomenka requested changes
Please make updates due to my comments.

2020-11-23 16:21 UTC, KirylParkhomenka commented on cypress/page_object/HomePage.js
> +  openPage(webPage){
Use simple naming of parameters.
Use `url` instead of `webPage`

2020-11-23 16:21 UTC, KirylParkhomenka commented on cypress/integration/home_page.spec.js
> +      cy.wrap(item).contains(navigation_menu.CLINICAL_SUMMARIES_SECTION[index]);
Please try to implement line 18 in the next way:
```
cy.wrap(item).invoke('text').then(text => {
  expect(text).to.equal(navigation_menu.CLINICAL_SUMMARIES_SECTION[index])
})
```
You will use strict comparison instead of  simple `contain`.

2020-11-24 08:02 UTC, KirylParkhomenka approved these changes
Good job!

2020-11-24 13:26 UTC, merged